definitions:
  handler.request:
    properties:
      activo:
        type: boolean
      altura:
        type: integer
      apellido:
        type: string
      edad:
        type: integer
      email:
        type: string
      fecha:
        type: string
      id:
        type: integer
      nombre:
        type: string
    type: object
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /usuarios:
    get:
      consumes:
      - application/json
      description: get usuarios
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: GetAll usuarios
      tags:
      - Usuario
    post:
      consumes:
      - application/json
      description: store usuarios
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product to store
        in: body
        name: usuario
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Store usuarios
      tags:
      - Usuario
  /usuarios/{id}:
    delete:
      consumes:
      - application/json
      description: delete usuario by id
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: User ID to delete
        in: query
        name: string
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Delete usuarios
      tags:
      - Usuario
    patch:
      consumes:
      - application/json
      description: update apellido y edad de un usuario
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: User ID to update name and age
        in: query
        name: string
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: UpdateApellidoEdad usuarios
      tags:
      - Usuario
    put:
      consumes:
      - application/json
      description: Update usuario
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Usuario to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      - description: Usuario ID to Update
        in: query
        name: string
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update usuarios
      tags:
      - Usuario
swagger: "2.0"
